behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    behavior_types: ["BackUp", "Wait"]
    transform_tolerance: 0.1

bt_navigator_server:
  ros__parameters:
    use_sim_time: True
    global_frame: "map"
    robot_frame: "base_footprint"
    transform_tolerance: 0.1
    odom_topic: "/odometry/filtered"
    plugin_lib_names: [
      "follow_path_action_bt_node",
      "compute_path_to_pose_action_bt_node",
      "pipeline_sequence_bt_node",
      "recovery_bt_node",
      "round_robin_bt_node",
      "wait_action_bt_node",
      "back_up_action_bt_node",
      "clear_costmap_service_bt_node",
      "goal_updated_condition_bt_node",
      "rate_controller_bt_node"
    ]
    navigator_type: "bt_navigators::NavigateToPoseNavigator"
    NavigateToPoseNavigator:
      goal_blackboard_id: "goal"
      path_blackboard_id: "path"
      default_bt_xml_filename: "/home/dev_ws/install/bt_navigators/share/bt_navigators/behavior_trees/navigate_to_pose_w_recovery.xml"
    # for preventing timeout during debugging session
    # server_timeout: -1
    # wait_for_service_timeout: -1

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_type: a_star_planner::AStarGlobalPlanner

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    controller_type: "dwa_core::DWALocalPlanner"
    odom_topic: "odometry/filtered"
    GoalChecker:
      xy_tolerance: 0.25
      yaw_tolerance: 3.14 # no angle check
    ProgressChecker:
      minimum_distance: 0.1
      movement_time_allowance: 5.0
    DWALocalPlanner:
      vx_samples: 8
      vy_samples: 8
      vtheta_samples: 10
      sim_time: 1.7
      time_granularity: 0.1
      debug: True
      min_vel_x: -0.3
      max_vel_x: 0.3
      decel_x: -2.5
      acc_x: 2.5
      min_vel_y: -0.3
      max_vel_y: 0.3
      decel_y: -2.5
      acc_y: 2.5
      min_vel_theta: -0.3
      max_vel_theta: 0.3
      decel_theta: -2.5
      acc_theta: 2.5
      critic_names: [
        "GlobalPathAlign", 
        "ObstacleProximity", 
        # "PathLength"
      ]
      GlobalPathAlign:
        weight: 1.3
        invert_score: true
      ObstacleProximity:
        weight: 2.0
        invert_score: true
      # PathLength:
      #   weight: 0.3
      #   invert_score: false

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 6.0
    laser_min_range: 0.12
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.24
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.24
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: True
      robot_radius: 0.24
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.0
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: True
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""
